// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import {
  EncodeObject, GeneratedType, OfflineSigner, Registry,
} from "@cosmjs/proto-signing";
import { msgTypes } from "./registry";
import { IgniteClient } from "../client";
import { MissingWalletError } from "../helpers";
import { Api } from "./rest";

import {
  Tx as typeTx, TxRaw as typeTxRaw, SignDoc as typeSignDoc, TxBody as typeTxBody, AuthInfo as typeAuthInfo, SignerInfo as typeSignerInfo, ModeInfo as typeModeInfo, ModeInfo_Single as typeModeInfo_Single, ModeInfo_Multi as typeModeInfo_Multi, Fee as typeFee,
} from "./types";

export { };

export const registry = new Registry(msgTypes);

type Field = {
  name: string;
  type: unknown;
};
function getStructure(template) {
  const structure: { fields: Field[] } = { fields: [] };
  for (const [key, value] of Object.entries(template)) {
    const field = { name: key, type: typeof value };
    structure.fields.push(field);
  }
  return structure;
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
  prefix: string
  signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => ({

});

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => new Api({ baseURL: addr });

class SDKModule {
  public query: ReturnType<typeof queryClient>;

  public tx: ReturnType<typeof txClient>;

  public structure: Record<string, unknown>;

  public registry: Array<[string, GeneratedType]> = [];

  constructor(client: IgniteClient) {
    this.query = queryClient({ addr: client.env.apiURL });
    this.updateTX(client);
    this.structure = {
      Tx: getStructure(typeTx.fromPartial({})),
      TxRaw: getStructure(typeTxRaw.fromPartial({})),
      SignDoc: getStructure(typeSignDoc.fromPartial({})),
      TxBody: getStructure(typeTxBody.fromPartial({})),
      AuthInfo: getStructure(typeAuthInfo.fromPartial({})),
      SignerInfo: getStructure(typeSignerInfo.fromPartial({})),
      ModeInfo: getStructure(typeModeInfo.fromPartial({})),
      ModeInfo_Single: getStructure(typeModeInfo_Single.fromPartial({})),
      ModeInfo_Multi: getStructure(typeModeInfo_Multi.fromPartial({})),
      Fee: getStructure(typeFee.fromPartial({})),

    };
    client.on("signer-changed", (signer) => {
		 this.updateTX(client);
    });
  }

  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? "cosmos",
    });

    this.tx = methods;
    for (const m in methods) {
      this.tx[m] = methods[m].bind(this.tx);
    }
  }
}

const Module = (test: IgniteClient) => ({
  module: {
    CosmosTxV1Beta1: new SDKModule(test),
  },
  registry: msgTypes,
});
export default Module;
